name: main

on:
    push:
        branches:
            - master
            - responsive
    workflow_dispatch:

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code from repository
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
    test:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Fetch code from repository
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Test code
              run: npm test
              working-directory: .
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Fetch code from repository
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build from code
              run: npm run build
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: build-artifact
                path: ./build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: build-artifact
            - name: Debugging pwd
              run: pwd
            - name: Debugging ls -la
              run: ls -la
            